### ISSUE TITLE
fig_6_8 example code references wrong array in kernel loop

### ISSUE THREAD

**Issue by jnorwood** [Apress/data-parallel-CPP#19]
The read_only_data is allocated as malloc_shared, but, instead, the uninitialized data is accessed in the kernel loop of fig_6_8.

![fig_6_8](https://user-images.githubusercontent.com/1499591/124822422-7ab6e780-df35-11eb-9c65-4dbbce18d623.png)

Aside from that, the prefetch does almost nothing to impact the execution time of this example, so it needs a better example.  I added multi-loop time measurements and tried several modifications of the code to effectively create pre-fetches.  I'll attach my test code.  

[fig_6_8_prefetch_memadvise_tests.zip](https://github.com/Apress/data-parallel-CPP/files/6779856/fig_6_8_prefetch_memadvise_tests.zip)

This shows the code added to use a read to cause the prefetch, along with the times for setup (to do the prefetches), followed by times of multiple passes of write to the data array.  Note that the times are all about the same after the initial prefetches, so apparently  the buffer sizes selected aren't really a good test case for use of prefetch.

![fig_6_8_tests](https://user-images.githubusercontent.com/1499591/124823830-3e848680-df37-11eb-9d2f-1297a245c242.png)

**Comment by mkinsner** [comment]
Thanks for the issue.  We've updated the sample to initialize `data`.  Prefetch is a hint to the implementation, so impact will depend on many things including toolchain maturity and whether equivalent optimizations are performed automatically.  The example aims to demonstrate how to use prefetch, but whether there is a measurable impact can't be guaranteed since people run on different devices and implementations.
