### ISSUE TITLE
Mistakes in the "Data Parallel C++" book and sample programs

### ISSUE THREAD

**Issue by breyerml** [Apress/data-parallel-CPP#8]
First of all, I wanted to say that I really liked reading your book. It would have been a great help back when I started learning SYCL for my master thesis.

However, while reading, I found a few mistakes and wanted to share them with you (if this is the wrong place or inappropriate please let me know):
- On page 167 in figure 6-8: you create the `read_only_data` array, initialize it, and explicitly tell the runtime that this array is read-only used in the kernel (using the `mem_advise` function). However, in the example code (as well as in the code samples) you never access the `read_only_data` array in the kernel (which, hence, is never used). I guess the kernel instead of being
```
Q.parallel_for(range{BLOCK_SIZE}, e, [=](id<1> i) {
    data[b * BLOCK_SIZE + i] += data[i];
});
```
should be
```
Q.parallel_for(range{BLOCK_SIZE}, e, [=](id<1> i) {
    data[b * BLOCK_SIZE + i] += read_only_data[i];
});
```
(see [PR #5](https://github.com/Apress/data-parallel-CPP/pull/5))
- On page 232 in figure 9-13: the first time a lambda kernel function is explicitly named (`<class MatrixMultiplication>`). However, the naming of lambda kernels is first explained 15 pages later on (page 247 in figure 10-4).
- On page 265 in figure 11-1: the first and third code lines are missing comment blocks (before `vec Class declaration` and `vec Class Members`).
- On page 267 in figure 11-5: the first operator example has a superfluous comma and brace and a missing comma in its parameter list:
```
template <typename dataT, int numElements>
vec<dataT, numElements>
operatorOP(const dataT, &lhs)
  const vec<dataT, numElements> &rhs);
```
should be
```
template <typename dataT, int numElements>
vec<dataT, numElements>
operatorOP(const dataT &lhs,
  const vec<dataT, numElements> &rhs);
```
- On page 272: in the second last line, "[...] *will vectorize* [...])", contains wrongly colored characters (link color).
- On page 310 in figure 13-5: the links are not clickable (since the whole table isn't clickable/selectable). Other tables aren't clickable too, however this one contains hyperlinks.
- On page 330: the exclusive interval should read `[0, i)` (or `[0, i[`) instead of `[0, i)]`.
- On page 342/343 in figures 14-14 and 14-15: the *offsets* to the SYCL kernel were deprecated in the SYCL 2020 specification. I guess this happened after this book was finished. However, with the current DPC++ compiler (2021.1 (2020.10.0.1113)) the respective code samples don't work correctly anymore. To fix this, the offset must be applied by hand (see [PR #6](https://github.com/Apress/data-parallel-CPP/pull/6)).
- On page 399 figure 16-6: the assert statement 
```
assert(vecA.size() == vecB.size() == vecC.size());
```
should be (already correct in the code samples)
```
assert(vecA.size() == vecB.size() && vecB.size() == vecC.size());
```
- In the code sample for figure 16-5: the number of loaded bytes for the vector triad is saved as `int`. This causes an integer overflow (resulting in a negative bandwidth) when entering an `array_size` larger than `89'478'485`. However, I had to use an `array_size` of `100'000'000` to get representative runtimes (~0.15s). Changing the type of the `triad_byte` variable to `std::size_t` should fix this issue (see [PR #7](https://github.com/Apress/data-parallel-CPP/pull/7)).
- On page 415: I couldn't find anything regarding the compiler macro `D__SYCL_DISABLE_ID_TO_INT_CONV__`. However, I found the compiler flag `-fsycl-id-queries-fit-in-int` that seems to fulfill the same purpose.
- On page 536 Ep-4: there is an additional newline after the template declaration and before the struct.
- In some code examples you use the `intel::` namespace. However, to be able to compile the respective code samples the `ONEAPI` or `INTEL` namespaces must be used. Are there efforts made to introduce all this functionality in a unified `intel::` namespace and therefore you used the later in the example codes in the book?

More personal opinion based points regarding the code examples:
- On page 416 in figure 16-18: you used `int vals[] = {300, 200, 100, 000};` Personally, I wouldn't use `000` but `0` (I guess you used `000` here for a better alignment with the other numbers). However, I don't believe that the majority of new C++ programmers know that number literals starting with a `0` are represented as octal numbers. So they will be surprised when playing around with the samples and changing, e.g., `000` to `012` and realizing that `012 != 12`.
- Same code examples are rather inconsistent compared to each other, e.g.:
  - You mentioned the `sycl::buffer::get_access` method on page 185, but only ever used it in one code example on page 405 (figure 16-10).
  - Sometimes you use the STL algorithms `std::fill` and `std.::iota` and sometimes plain `for`-loops
  - Sometimes you use `item.get_global_id(0)` and sometime `item.get_global_id()[0]`. I know that the former is more or less syntactic sugar for the later. However, they could possible do different things resulting in the reader thinking, why sometimes one version is preferred over the other.
  - Sometimes constructs are used that are more often found in C than in C++ (e.g., `DBL_MAX` on page 399 instead of `std::numeric_limits<double>::max()` or "normal" C malloc (not USM malloc) in some provided code samples).

And last but not least, one question out of curiosity:
on page 243 in figure 10-1 you mentioned that one disadvantage of lambda expressions is that they can't be templated. C++20 introduced templated lambdas (see https://en.cppreference.com/w/cpp/language/lambda), e.g.,:
```
auto glambda = []<class T>(T a, auto&& b) { return a < b; };
```
Do you know, whether there are any plans for future SYCL/DPC++ versions to also support templated lambdas?

**Comment by mkinsner** [comment]
Thanks for your comments, and this is a great place to provide them.  We'll incorporate into the errata.

> Do you know, whether there are any plans for future SYCL/DPC++ versions to also support templated lambdas?

I can't comment on exactly what future SYCL will adopt, but you should roughly expect it to track C++ with a few year delta (to enable deployed compilers to be caught up).  The goal of SYCL is in part to run ahead of C++ with heterogeneous compute features, so it aims to remain closely aligned with C++ evolution.  SYCL 2020 is based on C++17 and pulled in a few C++20 features (e.g. std::bit_cast).  You should expect that trend to continue.

**Comment by arkantos493** [comment]
Thank you for the fast reply. Nice to hear that SYCL/DPC++ tries to stay up to date with the current/upcoming C++ standards.

Adding to my post yesterday, I possibly found two additional "problems".
However, this time, I'm not really sure if these are real problems or misunderstandings from my side.

- In figures 1-3 (page 17), figure 3-4 (page 69), and figure 6-6 (page 163) you use `sycl::queue::memcpy` and `sycl::handler::memcpy`. In all examples one of the source or destination pointers is a pointer obtained by an USM allocation. The other pointer is obtained by "normal" host allocations. As of the SYCL2020 standard that should be fine ("Copies numBytes of data from the pointer src to the pointer dest. Both dest and src may be **either host or USM pointers**. For more detail on USM, please see Section4.8.", page 301). However, according to the DPC++ Runtime documentation "Copies data from one memory region to another, **both pointed by USM pointers**." (https://intel.github.io/llvm-docs/doxygen/classcl_1_1sycl_1_1handler.html#a110067774f86c17741d3dbcaba51de0c). So according to this documentation the code snippets should be UB? I guess, that this is currently a limitation in DPC++ (which would make the `sycl::*::memcpy` operations rather useless I guess)?
I stumbled upon `memcpy` while I played with the code sample *fig_1_1_hello.cpp*: I tried to change to `std::string` to a `std::string_view`. While this worked with `std::memcpy`, `sycl::queue::memcpy` and `sycl::handler::memcpy` resulted in garbage values copied to the USM pointer (https://community.intel.com/t5/Intel-oneAPI-Base-Toolkit/sycl-queue-memcpy-sycl-handler-memcpy-with-std-string-view-and/m-p/1258765#M1120).

- In the code sample for figure 18-13 (on page 490) you use "normal" `accessor` for filling the buffers. However, I thought that these accessor can only be used inside a command group; if you wan't to access a buffer on the host you have to use a `host_accessor`. At least, if I run the code snippet as it is (`accessor`) it results in `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`. After changing the accessors to `host_accessor` the code snippet runs correctly. So I guess that this is a bug and the code tries to access non-existing values on the device.
(Additionally I had to change a few other things to be able to compile the code snipped using the current DPC++ compiler because of the oneTBB revamp (https://community.intel.com/t5/Intel-oneAPI-Threading-Building/tbb-task-has-not-been-declared/m-p/1255723). I had to add a `#define PSTL_USE_PARALLEL_POLICIES 0` at the beginning of the file, add a namespace alias `namespace dpstd = dpl;` since with the mentioned `define` set the compiler was unable to find the dpstd namespace, and I had to change `dpstd::execution::default_policy` to `queue{}` since former is not defined in the `dpl` namespace according to the compiler.)
